### ISSUE TITLE
Abelton Link output does not work on the newest version (as a bpm signal for Carabiner or Wolfmix)

### ISSUE THREAD

**Issue by Jones-009** [grufkork/rkbx_osc#5]
Hi,

Abelton Link output does not work on the newest version (as a bpm signal for Carabiner or Wolfmix)
The Beat grid in the command prompt is correct (changing speed in the correct way) and the peers are established. It stays the howl time at 20 bpm and does not change i dont know if it is an user error but i would be thankful on help. The program is the only of its kind that i found and i would need it for my light shows.

Best Regards Jones 
![image](https://github.com/grufkork/rkbx_osc/assets/86669791/6360f59a-9fc2-4858-b39b-163f57dc64ed)

**Comment by grufkork** [comment]
Hm, I've mainly tested link functionality with Ableton. It might be a bit forceful with setting the next beat, maybe not all implementations like that. I'll look into it tomorrow 👍

**Comment by Jones-009** [comment]
Thank You very much

**Comment by grufkork** [comment]
Never mind, it seems I slipped when entering the offset for the BPM. It's fixed now! Try running `rkbx_osc.exe -u` to update, or if defender complains, just download the latest offsets file here: https://raw.githubusercontent.com/grufkork/rkbx_osc/master/offsets

**Comment by Jones-009** [comment]
Thankyou I try it wen im home

**Comment by grufkork** [comment]
Github can have some caching problems, try checking manually that you offsets file matches the one I linked. What happens when the memory offsets are off, is it reads a completely random BPM value which is then clamped by Link to [20,999].

**Comment by Jones-009** [comment]
sorry but where do i find the ofset file on my computer

**Comment by grufkork** [comment]
Just place it next to the executable - there should already be a file there. By now the caches should be up to date though, try just running `rkbx_osc.exe -u` again

**Comment by grufkork** [comment]
@Jones-009, did you get it to work? I'd love to see what you're making with the tool!

**Comment by Jones-009** [comment]
Thanks I try it and Tell you

**Comment by Jones-009** [comment]
![image](https://github.com/grufkork/rkbx_osc/assets/86669791/0a9e8d14-9e06-49d2-b96d-67248e3b0a95)
i dont now why but i try it in a hour with the offsetfile in the location at the exe (/downloads)

**Comment by Jones-009** [comment]
now it is working thank you very much 
![image](https://github.com/grufkork/rkbx_osc/assets/86669791/40c6b436-b4d5-49aa-9235-564994b192f2)

**Comment by Jones-009** [comment]
I posted this projekt in a forum i hope that this is fine

**Comment by Jones-009** [comment]
i dont know why but now its giving me the strange bpm again (999)
