### ISSUE TITLE
it is again Stuck on (999) bpm I tryed alredy to Update and put in the offset file manualy

### ISSUE THREAD

**Issue by Jones-009** [grufkork/rkbx_osc#6]
I don't know why but it would be great if you had a fix for tomorrow.

**Comment by grufkork** [comment]
Strange... I hate to say it, but it works on my machine :P 

To begin with, try deleting both `rkbx_osc.exe` and `offsets` and downloading it again from the releases page. What Rekordbox version are you using? 6.8.5 is the one I'm working on currently.

If it still doesn't work, try this version: [rkbx_osc.zip](https://github.com/grufkork/rkbx_osc/files/15160557/rkbx_osc.zip). It has a BPM display in the terminal, check if that is correct. I'd like to see if there's a problem with reading the BPM or if it's an issue with Link. If the reading is wrong, the BPM should either be a tiny number or a really big one.

**Comment by Jones-009** [comment]
;p i use the latest version 6.8.5 aswell i try and tell you

**Comment by Jones-009** [comment]
hi its giving me this 
![image](https://github.com/grufkork/rkbx_osc/assets/86669791/8d75a537-a4dc-4b9a-9817-d0dc779cc86a)

**Comment by grufkork** [comment]
Very strange... I wonder if something changed in Rekordbox. I'm getting the same thing. It works on my computer for a couple of restarts after I've changed the offsets, but today it broke for me again. I thought I had simply copied some values incorrectly, but that does not seem to be the case. Looking at it now

**Comment by grufkork** [comment]
Alright, I've redone it now, try downloading [the file](https://raw.githubusercontent.com/grufkork/rkbx_osc/master/offsets) now. `rkbx_osc.exe -u` will probably fail for a while because of the cache.

**Comment by Jones-009** [comment]
now it is working i hope it stays like that
:P

**Comment by grufkork** [comment]
Nice, I'll keep checking if something breaks.

**Comment by Jones-009** [comment]
Hi i have a question if rekordbox 7 will be suported soon it would be great.

**Comment by grufkork** [comment]
Eventually, not sure yet. I'm holding off installing it for a couple of days if some bug that reformats your entire library crops up. After that I'll see if something has changed significantly under the hood, or if the program still works in its current form. If nothing has changed, expect a couple of days 👍

**Comment by Jones-009** [comment]
👍

**Comment by grufkork** [comment]
@Jones-009 Offsets for 7.0.0 and 7.0.1 are up! You will need to download a .exe though, had to change a couple of things.

**Comment by Jones-009** [comment]
Ok thankyou very much. That's big help.
