### ISSUE TITLE
New Update came out  for RB 7.03

### ISSUE THREAD

**Issue by josodubz** [grufkork/rkbx_osc#7]
Will there be an update to the file for 7.03? Is it hard to change the target source myself?

**Comment by grufkork** [comment]
I always get notified of new RB versions from the multitude of messages like this I get from all corners of the internet 😁

I might have time to look at it tonight. Otherwise, if you've got any experience with Cheat Engine it shouldn't be too difficult following the readme. If you haven't already you can try using the 7.0.2 offsets, sometimes the old one works.

**Comment by josodubz** [comment]
I'm sorry to be one of those also thanks for the quick response!
Definintely didn't mean to disturb you or make you think I'm being
impatient! Sorry mate! Thanks for the reply.

**Comment by grufkork** [comment]
No no it's great, I'm staying on 6.8.5 so it's the only way for me to know 👍

**Comment by josodubz** [comment]
Surprisingly I haven't had any of the issues that people are saying with 7
and the proceeding updates! So I bounce between 6.8.5 and 7. Think only
thing I found was just stuff with playing tracks from streaming services
wasn't great but yeah. I'll fiddle around with this and see if I can get it
working!

**Comment by grufkork** [comment]
New offsets are out, just do `rkbx_osc.exe -u` and it should update itself. The timing seems to have gotten a jittery with v7+ compared to 6.8.5, but I'm not really sure why. It might be that I've for some reason picked bad values to track by, but there isn't really any others to choose from. It should be good enough for visuals, but not for music. I'll look closer at it eventually, together with some kind of 1.0 release. If you have time, could you try playing a link-synced clicktrack on your setup and if it jumps around/sync badly?
